# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
date_format: "ordinal"
title: 蔡建斌的博客
subtitle: "公众号：拔菜集"
description: "敏捷软件研发百态。我们永远在通往「出来拔菜」的路上奔跑。"
keywords: 蔡建斌, 敏捷, 拔菜
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: johncai/johncai.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true

# ---------------- #
#      Author      #
# ---------------- #
author: 蔡建斌
organization: 
organization_url: 
github_username: johncai
location: Shanghai, China
email: caijianbin93@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: none

# https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: johncai
#     repo: blog-comments
#     clientID: 1fb7a6b8723de02144ec
#     clientSecret: acd7c13ce41279076c2f0c273095a5007f9e5e19
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
#     adsense:
#         footer: true
#         sidebar: true 
#         content_header: true
#         content_footer: false

